//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
// Generated by EntityQueryBuilder_With.tt

using Unity.Collections;
using Unity.Collections.LowLevel.Unsafe;

namespace Unity.Entities
{
    public partial struct EntityQueryBuilder
    {
        // ** FLUENT QUERY **

        public EntityQueryBuilder WithAny<T0>()
        {
            ValidateHasNoQuery();
            m_Any.Add(TypeManager.GetTypeIndex<T0>());
            return this;
        }

        public EntityQueryBuilder WithAny<T0, T1>()
        {
            ValidateHasNoQuery();
            m_Any.Add(TypeManager.GetTypeIndex<T0>());
            m_Any.Add(TypeManager.GetTypeIndex<T1>());
            return this;
        }

        public EntityQueryBuilder WithAny<T0, T1, T2>()
        {
            ValidateHasNoQuery();
            m_Any.Add(TypeManager.GetTypeIndex<T0>());
            m_Any.Add(TypeManager.GetTypeIndex<T1>());
            m_Any.Add(TypeManager.GetTypeIndex<T2>());
            return this;
        }

        public EntityQueryBuilder WithAny<T0, T1, T2, T3>()
        {
            ValidateHasNoQuery();
            m_Any.Add(TypeManager.GetTypeIndex<T0>());
            m_Any.Add(TypeManager.GetTypeIndex<T1>());
            m_Any.Add(TypeManager.GetTypeIndex<T2>());
            m_Any.Add(TypeManager.GetTypeIndex<T3>());
            return this;
        }

        public EntityQueryBuilder WithAny<T0, T1, T2, T3, T4>()
        {
            ValidateHasNoQuery();
            m_Any.Add(TypeManager.GetTypeIndex<T0>());
            m_Any.Add(TypeManager.GetTypeIndex<T1>());
            m_Any.Add(TypeManager.GetTypeIndex<T2>());
            m_Any.Add(TypeManager.GetTypeIndex<T3>());
            m_Any.Add(TypeManager.GetTypeIndex<T4>());
            return this;
        }

        public EntityQueryBuilder WithNone<T0>()
        {
            ValidateHasNoQuery();
            m_None.Add(TypeManager.GetTypeIndex<T0>());
            return this;
        }

        public EntityQueryBuilder WithNone<T0, T1>()
        {
            ValidateHasNoQuery();
            m_None.Add(TypeManager.GetTypeIndex<T0>());
            m_None.Add(TypeManager.GetTypeIndex<T1>());
            return this;
        }

        public EntityQueryBuilder WithNone<T0, T1, T2>()
        {
            ValidateHasNoQuery();
            m_None.Add(TypeManager.GetTypeIndex<T0>());
            m_None.Add(TypeManager.GetTypeIndex<T1>());
            m_None.Add(TypeManager.GetTypeIndex<T2>());
            return this;
        }

        public EntityQueryBuilder WithNone<T0, T1, T2, T3>()
        {
            ValidateHasNoQuery();
            m_None.Add(TypeManager.GetTypeIndex<T0>());
            m_None.Add(TypeManager.GetTypeIndex<T1>());
            m_None.Add(TypeManager.GetTypeIndex<T2>());
            m_None.Add(TypeManager.GetTypeIndex<T3>());
            return this;
        }

        public EntityQueryBuilder WithNone<T0, T1, T2, T3, T4>()
        {
            ValidateHasNoQuery();
            m_None.Add(TypeManager.GetTypeIndex<T0>());
            m_None.Add(TypeManager.GetTypeIndex<T1>());
            m_None.Add(TypeManager.GetTypeIndex<T2>());
            m_None.Add(TypeManager.GetTypeIndex<T3>());
            m_None.Add(TypeManager.GetTypeIndex<T4>());
            return this;
        }

        public EntityQueryBuilder WithAll<T0>()
        {
            ValidateHasNoQuery();
            m_All.Add(TypeManager.GetTypeIndex<T0>());
            return this;
        }

        public EntityQueryBuilder WithAll<T0, T1>()
        {
            ValidateHasNoQuery();
            m_All.Add(TypeManager.GetTypeIndex<T0>());
            m_All.Add(TypeManager.GetTypeIndex<T1>());
            return this;
        }

        public EntityQueryBuilder WithAll<T0, T1, T2>()
        {
            ValidateHasNoQuery();
            m_All.Add(TypeManager.GetTypeIndex<T0>());
            m_All.Add(TypeManager.GetTypeIndex<T1>());
            m_All.Add(TypeManager.GetTypeIndex<T2>());
            return this;
        }

        public EntityQueryBuilder WithAll<T0, T1, T2, T3>()
        {
            ValidateHasNoQuery();
            m_All.Add(TypeManager.GetTypeIndex<T0>());
            m_All.Add(TypeManager.GetTypeIndex<T1>());
            m_All.Add(TypeManager.GetTypeIndex<T2>());
            m_All.Add(TypeManager.GetTypeIndex<T3>());
            return this;
        }

        public EntityQueryBuilder WithAll<T0, T1, T2, T3, T4>()
        {
            ValidateHasNoQuery();
            m_All.Add(TypeManager.GetTypeIndex<T0>());
            m_All.Add(TypeManager.GetTypeIndex<T1>());
            m_All.Add(TypeManager.GetTypeIndex<T2>());
            m_All.Add(TypeManager.GetTypeIndex<T3>());
            m_All.Add(TypeManager.GetTypeIndex<T4>());
            return this;
        }

    }
}
